// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Playlist struct {
	ID        int32
	UserID    int32
	SpotifyID string
	Name      string
}

type PlaylistArtist struct {
	ID         int32
	PlaylistID int32
	SpotifyID  string
	Name       string
}

type User struct {
	ID           int32
	DisplayName  pgtype.Text
	Email        pgtype.Text
	SpotifyID    string
	AccessToken  string
	RefreshToken string
}
