// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: playlist.sql

package database

import (
	"context"
)

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (
  user_id,
  spotify_id,
  name
) VALUES ( $1, $2, $3 )
RETURNING id, user_id, spotify_id, name
`

type CreatePlaylistParams struct {
	UserID    int32
	SpotifyID string
	Name      string
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist, arg.UserID, arg.SpotifyID, arg.Name)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpotifyID,
		&i.Name,
	)
	return i, err
}
