root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/satpl_web"
cmd = "sqlc generate && templ generate && go build -o ./tmp/satpl_web ./cmd/web"
delay = 0
exclude_dir = ["assets", "tmp"]
exclude_file = ["internal/database/db.go", "internal/database/models.go"]
exclude_regex = [".*.sql.go", "_templ.go"]
execude_unchanged = false
follow_symlink = false
full_bin = ""
include_ext = ["go", "tpl", "templ", "tmpl", "html", "sql"]
log = "tmp/build.log"
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
